services:
  web:
    build: ./ecodeli
    container_name: ecodeli_web
    environment:
      APP_ENV: production
      APP_KEY: base64:LTQPaH2RL7uTwKOvvZcPi3Z9Ap1zGyZfN7omA8uxp+U=
      APP_DEBUG: 'false'
      APP_URL: https://localhost
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ecodeli_db
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - db
    networks:
      - internal

  api:
    build: ./ecodeli-api
    container_name: ecodeli_api
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ecodeli_db
      DB_USER: root
      DB_PASSWORD: secret
    depends_on:
      - db
    networks:
      - internal

  db:
    image: mariadb:10.5
    container_name: ecodeli_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ecodeli_db
    volumes:
      - db_data:/var/lib/mysql
      - ./ecodeli/install.sql:/docker-entrypoint-initdb.d/install.sql:ro
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: ecodeli_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/webroot:/var/www/certbot:ro
      - ./nginx/ssl:/etc/letsencrypt:ro
    depends_on:
      - web
      - api
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  db_data:
